import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../(website)/globals.css";
import { Locale } from "@/i18n.config";
import { Toaster } from "sonner";
import UseSessionProvider from "@/providers/UseSessionProvider";
import ReduxProvider from "@/providers/ReduxProvider";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import DashboardHeader from "./admin/_components/dashboard-header";
import getTrans from "@/lib/translation";
import { getServerSession } from "next-auth";
import { authOptions } from "@/server/authOptions";
import { ThemeProvider } from "@/components/theme-provider";
import { redirect } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default async function DashboardLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: Locale }>;
}>) {
  const locale = (await params).locale;
  const translations = await getTrans(locale);
  const session = await getServerSession(authOptions);

  if (!session) {
    return redirect(`${locale}/login`);
  }

  return (
    <html
      lang={locale}
      dir={locale === "ar" ? "rtl" : "ltr"}
      suppressHydrationWarning
    >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UseSessionProvider>
          <ReduxProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="light"
              enableSystem
              disableTransitionOnChange
            >
              <SidebarProvider>
                <AppSidebar props={{}} session={session} translations={translations} />
                <SidebarInset>
                  <DashboardHeader />
                  <main className="p-5">{children}</main>
                </SidebarInset>
              </SidebarProvider>

              <Toaster />
            </ThemeProvider>
          </ReduxProvider>
        </UseSessionProvider>
      </body>
    </html>
  );
}
